/// Tres ciclos distintos: status do motorista, tratativa da lideranca e aceite.
table fato_cinco_porques
	lineageTag: 75d855bf-d6a7-47f1-a01c-7c0cca0bfb3d

	column analise_id
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: cdacf703-d1b2-4023-a486-5c4a4be47005
		summarizeBy: sum
		sourceColumn: analise_id

		annotation SummarizationSetBy = Automatic

	column revenda_id
		dataType: string
		isHidden
		lineageTag: 950e1889-2964-4dec-b9df-01bce452e178
		summarizeBy: none
		sourceColumn: revenda_id

		annotation SummarizationSetBy = Automatic

	column colaborador_id
		dataType: string
		isHidden
		lineageTag: f4279f95-bdf9-4d94-a29d-8409da14ceb6
		summarizeBy: none
		sourceColumn: colaborador_id

		annotation SummarizationSetBy = Automatic

	column colaborador
		dataType: string
		lineageTag: 089b3781-7213-4e34-a87f-0bff602ef532
		summarizeBy: none
		sourceColumn: colaborador

		annotation SummarizationSetBy = Automatic

	column feedback_rota_id
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 01ae346a-c4ba-41dc-92dd-2d932a51e260
		summarizeBy: sum
		sourceColumn: feedback_rota_id

		annotation SummarizationSetBy = Automatic

	column rota
		dataType: string
		lineageTag: 4a85449c-e9e5-45ae-aeb9-dd76de10c15a
		summarizeBy: none
		sourceColumn: rota

		annotation SummarizationSetBy = Automatic

	column problema_id
		dataType: string
		isHidden
		lineageTag: 67910d30-75fd-47a5-95d6-c9e8d5c78716
		summarizeBy: none
		sourceColumn: problema_id

		annotation SummarizationSetBy = Automatic

	column problema
		dataType: string
		lineageTag: 17febcd1-9f8f-42e8-87f4-6fb69e830c7e
		summarizeBy: none
		sourceColumn: problema

		annotation SummarizationSetBy = Automatic

	column profundidade
		dataType: int64
		lineageTag: 46bdf17e-c7d7-45b1-9f57-b9005e6687a2
		summarizeBy: none
		sourceColumn: profundidade

		annotation SummarizationSetBy = Automatic

	column chegou_ao_quinto
		dataType: boolean
		lineageTag: 3a928193-c6b8-42c4-af1d-5cc0cb6e8a78
		summarizeBy: none
		sourceColumn: chegou_ao_quinto

		annotation SummarizationSetBy = Automatic

	column causa_raiz
		dataType: string
		lineageTag: 20c782d1-6070-47b2-aa6a-d07efe538714
		summarizeBy: none
		sourceColumn: causa_raiz

		annotation SummarizationSetBy = Automatic

	column categoria_id
		dataType: string
		isHidden
		lineageTag: b4946998-4886-41fd-8e25-40d263fa5540
		summarizeBy: none
		sourceColumn: categoria_id

		annotation SummarizationSetBy = Automatic

	column categoria
		dataType: string
		lineageTag: ee155d85-9539-4ee0-94b0-05a716f70143
		summarizeBy: none
		sourceColumn: categoria

		annotation SummarizationSetBy = Automatic

	column acao_sugerida
		dataType: string
		lineageTag: 6d5a6895-bf0a-4bc4-a298-5bb582194a58
		summarizeBy: none
		sourceColumn: acao_sugerida

		annotation SummarizationSetBy = Automatic

	column status
		dataType: string
		lineageTag: 62d33d4f-f706-4ec2-beea-17e676f5d2cc
		summarizeBy: none
		sourceColumn: status

		annotation SummarizationSetBy = Automatic

	column concluida
		dataType: boolean
		lineageTag: 0c2007f6-28d5-4995-ac16-234a0b4a7829
		summarizeBy: none
		sourceColumn: concluida

		annotation SummarizationSetBy = Automatic

	column tratativa_status
		dataType: string
		lineageTag: 85738ec3-2300-4bd8-ac69-9513e9344bd6
		summarizeBy: none
		sourceColumn: tratativa_status

		annotation SummarizationSetBy = Automatic

	column tratada
		dataType: boolean
		lineageTag: e7852eca-87ca-420a-9288-2b9c01004a70
		summarizeBy: none
		sourceColumn: tratada

		annotation SummarizationSetBy = Automatic

	column resposta_lideranca
		dataType: string
		lineageTag: 6ad886f8-3637-42b2-beb9-2417191c5343
		summarizeBy: none
		sourceColumn: resposta_lideranca

		annotation SummarizationSetBy = Automatic

	column respondida_lideranca
		dataType: boolean
		lineageTag: 59b0d8a1-f7b5-4154-a3ea-425f7b0a8ace
		summarizeBy: none
		sourceColumn: respondida_lideranca

		annotation SummarizationSetBy = Automatic

	column resposta_lideranca_em
		dataType: dateTime
		formatString: dd/MM/yyyy
		lineageTag: 1dc21d2e-1f9e-4356-9dba-fce46d4011b6
		summarizeBy: none
		sourceColumn: resposta_lideranca_em

		annotation SummarizationSetBy = Automatic

	column motorista_aceitou
		dataType: boolean
		lineageTag: 07d880e7-530d-42c2-9f2c-b09a44456eed
		summarizeBy: none
		sourceColumn: motorista_aceitou

		annotation SummarizationSetBy = Automatic

	column aceite_rotulo
		dataType: string
		lineageTag: cdb5462e-a52d-4dfa-baf1-80a928b23209
		summarizeBy: none
		sourceColumn: aceite_rotulo

		annotation SummarizationSetBy = Automatic

	column motorista_aceitou_em
		dataType: dateTime
		formatString: dd/MM/yyyy
		lineageTag: 08af354d-571d-41c2-8f88-60b3ebbb0269
		summarizeBy: none
		sourceColumn: motorista_aceitou_em

		annotation SummarizationSetBy = Automatic

	column tempo_segundos
		dataType: double
		lineageTag: 7ec55bff-6f69-464c-8663-7f1715e0ff51
		summarizeBy: sum
		sourceColumn: tempo_segundos

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column iniciada_em
		dataType: dateTime
		formatString: dd/MM/yyyy
		lineageTag: 194ba3b6-89cf-4e04-98e1-cda0d4ce8156
		summarizeBy: none
		sourceColumn: iniciada_em

		annotation SummarizationSetBy = Automatic

	column concluida_em
		dataType: dateTime
		formatString: dd/MM/yyyy
		lineageTag: 49c9abfc-7bef-4e6a-8955-49df6c7fec3c
		summarizeBy: none
		sourceColumn: concluida_em

		annotation SummarizationSetBy = Automatic

	column data
		dataType: dateTime
		formatString: dd/MM/yyyy
		lineageTag: 901508d0-b6b8-47cd-a85e-6467b4070f63
		summarizeBy: none
		sourceColumn: data

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column porques_respondidos
		dataType: int64
		lineageTag: e02afde7-aebe-4c89-9d92-1d644ba272b8
		summarizeBy: none
		sourceColumn: porques_respondidos

		annotation SummarizationSetBy = Automatic

	column horas_ate_resposta
		dataType: double
		lineageTag: 2feec9b1-08e2-4dbc-aa8d-ef60d9327a83
		summarizeBy: sum
		sourceColumn: horas_ate_resposta

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column horas_aguardando
		dataType: double
		lineageTag: cd68aad7-ebe3-4de8-8ab2-a964424c05f8
		summarizeBy: sum
		sourceColumn: horas_aguardando

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column chave
		dataType: string
		isHidden
		lineageTag: fb7c9d0c-abec-4e82-98ec-f279b44af246
		summarizeBy: none
		sourceColumn: chave

		annotation SummarizationSetBy = Automatic

	partition fato_cinco_porques = m
		mode: import
		source =
				let
				    Origem = PostgreSQL.Database(Servidor, Banco),
				    Dados = Origem{[Schema="bi",Item="fato_cinco_porques"]}[Data],
				    ComChave = Table.AddColumn(Dados, "chave", each
				        (if [revenda_id] = null then "" else Text.From([revenda_id]))
				        & "|" &
				        (if [colaborador_id] = null then "" else Text.From([colaborador_id])),
				        type text)
				in
				    ComChave

	annotation PBI_ResultType = Table

